FROM node:16.14.0-alpine3.15 as build

WORKDIR /usr/src/ezpaarse/middlewares
COPY ./middlewares ./

WORKDIR /usr/src/ezpaarse/doc
COPY ./doc ./
RUN npm install
ENV NODE_ENV=production
RUN npm run build

FROM nginx:1.21.6-alpine
COPY --from=build /usr/src/ezpaarse/doc/src/.vuepress/dist/ /usr/share/nginx/html/