version: '3'

services:

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.12.0
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    ports:
      - 7700:7700
    restart: unless-stopped

  scraper:
    container_name: meilisearch_docs_scraper
    image: getmeili/docs-scraper:v0.9.5
    volumes:
      - ./.vuepress/docs-scraper.config.json:/docs-scraper/config.json
    environment:
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      MEILISEARCH_HOST_URL: 'http://meilisearch:7700'
      MEILISEARCH_API_KEY: ''
    depends_on:
      - meilisearch
    command: pipenv run ./docs_scraper config.json