# ezpaarse docker-compose.yml dedicated to production
version: '3'

services:

  ezpaarse:
    container_name: ezpaarse
    image: ezpaarseproject/ezpaarse:3.11.0
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    environment:
      NODE_ENV: "production"
      EZPAARSE_MONGO_URL: "mongodb://ezpaarse_db:27017/ezpaarse"
    volumes:
      - ./platforms:/opt/ezpaarse/platforms
      - ./middlewares:/opt/ezpaarse/middlewares
      - ./resources:/opt/ezpaarse/resources
      - ./exclusions:/opt/ezpaarse/exclusions
      - ./config.local.json:/opt/ezpaarse/config.local.json
    ports:
      - 59599:59599
    depends_on:
      - ezpaarse_db
    restart: unless-stopped

  ezpaarse_db:
    image: mongo:7.0.20
    container_name: ezpaarse_db
    restart: unless-stopped
    volumes:
      - ./data/ezpaarse_db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "\"db.adminCommand('ping')\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
