#!/bin/sh
# Ensure all javascript files staged for commit pass standard code style
ROOT_DIR=$(git rev-parse --show-toplevel)
LINT="${ROOT_DIR}/node_modules/eslint/bin/eslint.js --ext .js"

JSFILES=`git diff --name-only --cached --relative | grep '\.js$'`

if [ -n "$JSFILES" ]; then
  echo "$JSFILES" | xargs node $LINT
  if [ $? -ne 0 ]; then exit 1; fi
fi

exit 0
