#!/bin/bash

PROJECT_NAME="ezpaarse"
SPRINT_NAME="sprint10"
SPRINT_START="2013-09-09"
SPRINT_END="2013-10-10"
GENERATE_VIDEO="0"

git log --pretty=format:user:%aN%n%at --reverse --raw --encoding=UTF-8 --no-renames --after $SPRINT_START --before $SPRINT_END > ./gource-git.log

if [ "$GENERATE_VIDEO" == "1" ]; then
  gource --seconds-per-day 2 \
         --file-filter ".*node_modules.*" \
         --output-framerate 60 \
         --user-scale 1.5 \
         --user-image-dir ./avatars/ \
         --path ./gource-git.log \
         -1280x720 -o - \
        | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libvpx -b 10000K gource-$PROJECT_NAME-$SPRINT_NAME.webm
else
  gource --seconds-per-day 2 \
         --file-filter ".*node_modules.*" \
         --output-framerate 60 \
         --user-scale 1.5 \
         --user-image-dir ./avatars/ \
         --path ./gource-git.log
fi